apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todos-api-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              serviceName: todos-api
              servicePort: 8082
  tls:
    - hosts:
        - localhost
      secretName: ingress-tls