apiVersion: v1
kind: Service
metadata:
  name: todos-api
  labels:
    app: todos-api
spec:
  ports:
    - port: 8082
      targetPort: 8082
      name: boot
  selector:
    app: todos-api
  type: LoadBalancer