apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: todos-api
build:
  artifacts:
    - image: triathlonguy/todos-api
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base-platform-api-0.3
        dependencies:
          paths:
            - src
            - pom.xml

#------------------------------------------
# Option 1
# deploy with Skaffold
deploy:
  kubectl:
    manifests:
      - kubernetes/app/deployment.yaml
      - kubernetes/app/service.yaml
      - kubernetes/app/ingress.yaml

#------------------------------------------
# Options 2
# deploy with Skaffold + Kustomize
#deploy:
#  kustomize:
#    paths: ["kubernetes/overlays/base"]
#profiles:
#  - name: qa
#    deploy:
#      kustomize:
#        paths: ["kubernetes/overlays/qa"]