todos:
  api:
    limit: 1024

logging:
  level:
    org:
      springframework: DEBUG

# running locally and connecting to backens in k8s?
# set the 2 properties below
cacheUrl: "http://104.154.253.234:8888"
backendUrl: "http://35.223.204.37:9090"

spring:
  application:
    name: todos-api
management:
  # Actuators
  # see https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints-exposing-endpoints
  # exposing endpoints config options
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
        exclude: prometheus
  endpoint:
    health:
      show-details: always
info:
  app:
    name: todos-api - Spring Boot Application
    description: TODOs - API - business logic w/ DB and cache access
server:
  port: 8082