management:
  metrics:
    export:
      wavefront:
        uri:proxy://taznu-observability-proxy:2878
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

wavefront:
  application:
    name: {{app-name}}
    service: {{app-name}}-service

logging.level:
  org.springframework.data: debug

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://any.uaa.uri/token_keys
