todos:
  api:
    limit: 1024

logging:
  level:
    org:
      springframework: INFO

# running locally and connecting to backend in k8s
cacheUrl: "http://store-backend-redis.default.svc.cluster.local:8888"
backendUrl: "http://store-backend-mysql.default.svc.cluster.local:9090"

spring:
  application:
    name: store-backend-api
management:
  #observability
  metrics:
    export:
      wavefront:
        uri: "http://wavefront.default.svc.cluster.local:9411"
  # Actuators
  # see https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints-exposing-endpoints
  # exposing endpoints config options
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
        exclude: prometheus
  endpoint:
    health:
      show-details: always
info:
  app:
    name: store-backend-api - Spring Boot Application
    description: Business logic sample for backend apis for online stores
# Use default 8080 port
# server:
#   port: 8082
