#@ load("@ytt:data", "data") 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: #@ data.values.artifactId
  name: #@ data.values.artifactId
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: #@ data.values.artifactId
  template:
    metadata:
      labels:
        app.kubernetes.io/name: #@ data.values.artifactId
        app.kubernetes.io/part-of: #@ data.values.artifactId
#@ if data.values.addAlv:
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.name: #@ data.values.artifactId + "-liveview"
#@ end
    spec:
      imagePullSecrets: 
      - name: imagereg-secret
      containers:
        - name: #@ data.values.artifactId
          image: #@ data.values.artifactId + ":latest"
          imagePullPolicy: Always
          env:
            - name: spring.profiles.active
              value: k8s
            - name: spring.security.oauth2.resourceserver.jwt.jwk-set-uri
              valueFrom:
                secretKeyRef:
                  name: #@ data.values.artifactId + "-jwk"
                  key: jwk-set-uri
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: #@ data.values.artifactId + "-service"
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: #@ data.values.artifactId
