apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-name
spec:
  selector:
    matchLabels:
      app: app-name
  template:
    metadata:
      labels:
        app: app-name
        tanzu.app.live.view: "true" #Enable pod to be discovered by connector
        tanzu.app.live.view.application.name: dekt4pets-backend-live-view 
    spec:
      imagePullSecrets: 
      - name: imagereg-secret
      containers:
        - name: app-name
          image: app-name:latest
          imagePullPolicy: Always
          env:
            - name: spring.profiles.active
              value: k8s
            - name: spring.security.oauth2.resourceserver.jwt.jwk-set-uri
              valueFrom:
                secretKeyRef:
                  name: app-name-jwk
                  key: jwk-set-uri
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: app-name-service
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: app-name
