apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml
  - ingress.yaml

# generate a config map from this kustomization file
configMapGenerator:
  - name: todos-api-config
    files:
      - application.yaml