apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: online-store-backend-route-config
spec:
  service: 
    name: online-store-backend-service
  routes:
    - predicates:
        - Path=/api/store-items
        - Method=GET
      filters:
        - StripPrefix=1
        - RateLimit=2,10s
    - ssoEnabled: true
      tokenRelay: true
      predicates:
        - Path=/api/whoami
        - Method=GET
      filters:
        - StripPrefix=1
    - ssoEnabled: true
      tokenRelay: true
      predicates:
        - Path=/api/store-item/*/transaction-requests/**
        - Method=POST,PUT,DELETE
      filters:
        - StripPrefix=1
    - predicates:
        - Path=/api/actuator/**
        - Method=GET
